#!/system/bin/sh

PID=`ps |grep camera|awk '{print $2}'`
if [[ ${#PID} -ne 0 ]]; then
        kill -9 $PID
fi
        
RET=1
while [[ $RET -ne 0 ]]; do
	am start -a android.intent.action.MAIN -n com.android.camera/.Camera
        RET=$?
done
sleep 2
PID=`ps |grep camera|awk '{print $2}'`
kill -9 $PID
exit 0
        
